#!/bin/bash

############################
# Config
############################

geoip_database="city"
mysql_host="localhost"
mysql_user="anope"
mysql_password="anope"
mysql_database="anope"
prefix="anope_"
die="no"

###########################

#geoip_country_source="http://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip"
#geoip_city_source="http://geolite.maxmind.com/download/geoip/database/GeoLiteCity_CSV/GeoLiteCity-latest.zip"
geoip_country_source="http://jens.anope.org/private/GeoIPCuntryCSV.zip"
geoip_city_source="http://jens.anope.org/private/GeoLiteCity-latest.zip"

###########################

PARAMS="--verbose --delete --local --default_character_set=latin1 --fields-terminated-by=, --fields-enclosed-by=\" --lines-terminated-by=\n --host=$mysql_host --user=$mysql_user --password=$mysql_password $mysql_database"

if test $die = "yes"; then
	echo "You have to edit this script first."
	exit
fi

if test $geoip_database = "country"; then
	wget -q -N $geoip_country_source
	unzip -j GeoIPCountryCSV.zip
	mv GeoIPCountryWhois.csv $prefix"geoip_country.csv"
	mysqlimport --columns=@x,@x,start,end,countrycode,countryname $PARAMS $prefix"geoip_country.csv"
	rm $prefix"geoip_country.csv" GeoIPCountryCSV.zip
elif test $geoip_database = "city"; then
	wget -q -N $geoip_city_source
	unzip -j GeoLiteCity-latest.zip
	mv GeoLiteCity-Blocks.csv $prefix"geoip_city_blocks.csv"
	mv GeoLiteCity-Location.csv $prefix"geoip_city_location.csv"
	mysqlimport --columns=start,end,locID $PARAMS $prefix"geoip_city_blocks.csv"
	mysqlimport --columns=locID,country,region,city,@x,latitude,longitude,@x,areaCode $PARAMS $prefix"geoip_city_location.csv"
	rm $prefix"geoip_city_blocks.csv" $prefix"geoip_city_location.csv" GeoLiteCity-latest.zip
fi